include ../make.inc
#################################################
### Defining Compiling variables              ###
#################################################


BASE = ${PWD}
CXX           = g++ -m32  -Wno-deprecated  -std=c++11
LD            = g++ -m32  -Wno-deprecated -std=c++11
INSTALL	      = /usr/bin/install
SHELL = /bin/sh

####################################
###                              ###
####################################

.PHONY: clean install HEPMC LHAPDF PYTHIA8 TAUOLA

install: HEPMC LHAPDF PYTHIA8 TAUOLA

clean:
	@echo "============================="


HEPMC:
	@cd hepmc/build/; \
	#../../HepMC-2.06.05/configure -prefix=${BASE}/hepmc/install -with-momentum=GEV -with-length=CM; \
	../../HepMC-2.06.11/configure -prefix=${BASE}/hepmc/install -with-momentum=GEV -with-length=CM; \
	make; \
	make check; \
	make install; \
	cd ../../;  

LHAPDF:
	@tar xvfz LHAPDF-6.2.1.tar.gz; \
	cd LHAPDF-6.2.1; \
	./configure --prefix=${BASE}/lhapdf/ --libdir=${BASE}/lhapdf/lib/; \
	make; \
	make install; \
	cd ../lhapdf/share/LHAPDF; \
	#mkdir PDFsets; \
	#cd PDFsets; \
	wget http://lhapdfsets.web.cern.ch/lhapdfsets/current/NNPDF30_nlo_as_0118.tar.gz -O -| tar -zxvf - -C "."; \
	wget http://lhapdfsets.web.cern.ch/lhapdfsets/current/NNPDF23_nlo_as_0119.tar.gz -O -| tar -zxvf - -C "."; \
	wget http://lhapdfsets.web.cern.ch/lhapdfsets/current/NNPDF23_nnlo_as_0119.tar.gz -O -| tar -zxvf - -C "."; \
	wget http://lhapdfsets.web.cern.ch/lhapdfsets/current/MSTW2008lo68cl.tar.gz -O -| tar -zxvf - -C "."; \
	wget http://lhapdfsets.web.cern.ch/lhapdfsets/current/MSTW2008nlo68cl.tar.gz -O -| tar -zxvf - -C "."; \
	wget http://lhapdfsets.web.cern.ch/lhapdfsets/current/MSTW2008nnlo68cl.tar.gz -O -| tar -zxvf - -C "."; \
	wget http://lhapdfsets.web.cern.ch/lhapdfsets/current/MSTW2008lo90cl.tar.gz -O -| tar -zxvf - -C "."; \
	wget http://lhapdfsets.web.cern.ch/lhapdfsets/current/MSTW2008nlo90cl.tar.gz -O -| tar -zxvf - -C "."; \
	wget http://lhapdfsets.web.cern.ch/lhapdfsets/current/MSTW2008nnlo90cl.tar.gz -O -| tar -zxvf - -C "."; \
	wget http://lhapdfsets.web.cern.ch/lhapdfsets/current/CT10.tar.gz -O -| tar -zxvf - -C "."; \
	wget http://lhapdfsets.web.cern.ch/lhapdfsets/current/CT10nlo.tar.gz -O -| tar -zxvf - -C "."; \
	wget http://lhapdfsets.web.cern.ch/lhapdfsets/current/CT10nnlo.tar.gz -O -| tar -zxvf - -C "."; \
	wget http://lhapdfsets.web.cern.ch/lhapdfsets/current/cteq66.tar.gz -O -| tar -zxvf - -C "."; \
	
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/6.2.1/cteq6mE.tar.gz -O -| tar -zxvf - -C "."; \

	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF30_nlo_as_0118.LHgrid; \
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nlo_as_0119.LHgrid; \
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/NNPDF23_nnlo_as_0119.LHgrid; \
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008lo68cl.LHgrid; \
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo68cl.LHgrid; \
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo68cl.LHgrid; \
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008lo90cl.LHgrid; \
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nlo90cl.LHgrid; \
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/MSTW2008nnlo90cl.LHgrid; \
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10.LHgrid; \
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nlo.LHgrid; \
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/CT10nnlo.LHgrid; \
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq66.LHgrid; \
	#wget http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1/cteq6mE.LHgrid; \
	
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 NNPDF30_nlo_as_0118.LHgrid; \
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 NNPDF23_nlo_as_0119.LHgrid; \
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 NNPDF23_nnlo_as_0119.LHgrid; \
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 MSTW2008lo68cl.LHgrid; \
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 MSTW2008nlo68cl.LHgrid; \
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 MSTW2008nnlo68cl.LHgrid; \
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 MSTW2008lo90cl.LHgrid; \
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 MSTW2008nlo90cl.LHgrid; \
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 MSTW2008nnlo90cl.LHgrid; \
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 CT10.LHgrid; \
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 CT10nlo.LHgrid; \
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 CT10nnlo.LHgrid; \
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 cteq66.LHgrid; \
	#../../../bin/lhapdf-getdata --repo=http://www.hepforge.org/archive/lhapdf/pdfsets/5.9.1 cteq6mE.LHgrid; \
	#wget http://cern.ch/alcaraz/cteq6ll.LHgrid; \
	cd ../../../../;

PYTHIA8:
	@cd pythia8303/; \
        ./configure --enable-shared --lcgplatform=x86_64-slc5-gcc43-opt --with-hepmc=${BASE}/hepmc/install/ --with-hepmcversion=2.06.11; \
        make;


TAUOLA:
	@cd TAUOLA/; \
	 ./configure --with-hepmc=${BASE}/hepmc/install/ --with-pythia8libs=${BASE}/pythia8303/ --with-lhapdf=${BASE}/lhapdf --with-tau-spinner ; \
	make all; make install; 
